AZURE_LOCATION: 'centralus'
RESOURCE_NAME_PREFIX: 'apimdemo1'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment-bdo'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/swati24may'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
